#!/bin/bash

USE_MODELSCOPE_HUB=1 accelerate launch src/train_bash.py \
    --stage sft \
    --do_train True \
    --model_name_or_path /home/symiao/.cache/modelscope/hub/modelscope/Llama-2-7b-ms \
    --finetuning_type lora \
    --template alpaca \
    --dataset_dir data \
    --dataset wikihowcnndmpubmed \
    --cutoff_len 1024 \
    --learning_rate 2e-05 \
    --num_train_epochs 1.0 \
    --max_samples 100000 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type cosine \
    --max_grad_norm 1.0 \
    --logging_steps 100 \
    --eval_steps 1000 \
    --save_steps 5000 \
    --warmup_steps 0 \
    --neftune_noise_alpha 0 \
    --lora_rank 8 \
    --lora_dropout 0.1 \
    --lora_target q_proj,v_proj \
    --output_dir saves/LLaMA2-7B/lora/train_3-1.samsum \
    --bf16 True \
    --val_size 0.1 \
    --evaluation_strategy steps \
    --eval_steps 5000 \
    --load_best_model_at_end True \
    --plot_loss True 